### ISSUE TITLE
Novu Installation Issue

### ISSUE THREAD

**Issue by althaf004** [SpikeeLabs/novu-python#18]
Hi, I was trying to install novu, but encountered below error.

```
❯ pip install novu
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.utils import int_from_bytes
ERROR: Could not find a version that satisfies the requirement novu (from versions: none)
ERROR: No matching distribution found for novu
```

Regards
Althaf

**Comment by nils-van-zuijlen** [comment]
Hello,

This package requires python 3.8 at least, using 3.6 is not supported, as [it is end of life since january 2022](https://devguide.python.org/versions/).

Also, please note that we are currently renaming the package to `novu-python` on request from the novu team as this is an unofficial library. See #17 for more info about that.

Regards,
Nils
